analyzer:
  _target_: obsei.analyzer.dummy_analyzer.DummyAnalyzer
analyzer_config:
  _target_: obsei.analyzer.dummy_analyzer.DummyAnalyzerConfig
sink:
  _target_: obsei.sink.slack_sink.SlackSink
sink_config:
  _target_: obsei.sink.slack_sink.SlackSinkConfig
source:
  _target_: obsei.source.reddit_source.RedditSource
source_config:
  _target_: obsei.source.reddit_source.RedditConfig
  subreddits:
  - smallbusiness
  lookup_period: 1h
