name: obsei action

on:
  push:
    branches:
      - main
  schedule:
   - cron: '*/60 * * * *'
  workflow_dispatch:
    inputs:
      logLevel:
        description: 'Log level'     
        required: true
        default: 'warning' 
        type: choice
        options:
        - info
        - warning
        - debug 
      tags:
        description: 'Test scenario tags'
        required: false 
        type: boolean
      environment:
        description: 'Environment to run tests against'
        type: environment
        required: true 
      

jobs:
  testing_workflow:
    environment: staging
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.7
          cache: 'pip'
          
      - name: Log python version
        run: |
            python -v

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Execute workflow
        env:
          REDDIT_USER: ${{secrets.REDDIT_USERNAME_JATIN}}
          REDDIT_PASS: ${{secrets.REDDIT_PASS_JATIN}}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN_OBSEI }}
          SLACK_CHANNEL_ID: ${{ secrets.SLACK_CHANNEL_OBSEI }}
          TEST_SECRET: ${{ secrets.TEST_SECRET }}
          TWITTER_BEARER_TOKEN: ${{ secrets.TWITTER_BEARER_TOKEN }}
          TWITTER_CONSUMER_KEY: ${{ secrets.TWITTER_CONSUMER_KEY }}
          TWITTER_CONSUMER_SECRET: ${{ secrets.TWITTER_CONSUMER_SECRET }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
        run: |
          python workflow.py
